## Lesson 4: Data Transformation with dplyr - Part 2 (Mutate, Summarize, Group By)

Welcome to Lesson 4! In Part 1, you learned how to **select**, **filter**, and **arrange** your data — the tools for *finding* the right data. Now we'll learn the tools for *calculating* with your data. These are the functions that turn raw transactions into the reports, dashboards, and KPIs that businesses actually use to make decisions.

---

### 🎯 What Will You Learn?

Think of these new tools like working with a spreadsheet:
- 🧮 **Mutate** = Adding a new formula column in Excel (e.g., Total = Price × Quantity)
- 📊 **Summarize** = Using SUM, AVERAGE, COUNT at the bottom of a spreadsheet
- 📂 **Group By** = Creating a Pivot Table that breaks data down by category

| Transformation | Real-World Analogy | R Function |
|---------------|-------------------|------------|
| Adding a calculated column | Writing a formula in a new Excel column | `mutate()` |
| Getting totals and averages | The "Summary" row at the bottom of a report | `summarize()` |
| Breaking down by category | A Pivot Table grouped by Region or Product | `group_by()` |
| Counting how many | Tallying items in each category | `count()` |

---

### 💼 Why Do Business Analysts Need These Tools?

Nobody in business looks at raw data. They look at **reports**, **summaries**, and **dashboards**. Here's the gap these tools fill:

| What Your Boss Asks | What You Need to Do | R Function |
|---------------------|---------------------|------------|
| "What's the total revenue per order?" | Multiply Price × Quantity for each row | `mutate()` |
| "Add a sales tax column at 8.25%" | Calculate a percentage of an existing column | `mutate()` |
| "Flag any orders over $500 for review" | Create a TRUE/FALSE column based on a condition | `mutate()` |
| "What was our average sale this quarter?" | Collapse all rows into one summary number | `summarize()` |
| "How do our regions compare?" | Get separate summaries for each region | `group_by() + summarize()` |
| "Which department has the most orders?" | Count rows by category | `count()` |

Every single one of these is something you'll be asked to do in your career — whether you work in marketing, finance, operations, supply chain, or consulting.

---

### 🔗 How This Connects to Part 1

In Lesson 3 (Part 1), you learned three tools. Today we add four more. Together, they form a complete analysis toolkit:

| Step | Action | Function | Lesson |
|------|--------|----------|--------|
| 1 | Pick the columns you need | `select()` | Part 1 |
| 2 | Keep only the rows that matter | `filter()` | Part 1 |
| 3 | **Add calculated columns** | **`mutate()`** | **Part 2 (today)** |
| 4 | **Break data into groups** | **`group_by()`** | **Part 2 (today)** |
| 5 | **Calculate summaries** | **`summarize()`** | **Part 2 (today)** |
| 6 | Sort the results | `arrange()` | Part 1 |

By the end of today, you'll be able to go from raw data to a finished business report using all six of these functions chained together.

---

### 📚 Lesson Structure (Two Class Periods)

| Period | Topics | What You'll Build |
|--------|--------|------------------|
| **Hour 1** | `mutate()`, `if_else()`, `case_when()`, building calculated fields | Enhanced transaction data with totals, taxes, and categories |
| **Hour 2** | `summarize()`, `group_by()`, `count()`, combined pipelines | Business dashboard with KPIs by region and product |

**🚀 By the end of this lesson**, you'll be able to build the kind of summary reports and KPI dashboards that businesses actually use to make decisions!

## Loading Required Packages

Just like in Lesson 3, we start by opening our toolbox. Every R session needs this step — think of it like logging into your work software at the start of each day.

---

### 🔧 Quick Reminder

```r
library(tidyverse)
```

| Code Part | What It Means |
|-----------|--------------|
| `library()` | "Load this package so I can use its functions" |
| `tidyverse` | The collection that includes dplyr (our data manipulation tool) |

**💡 Analogy**: Think of `library(tidyverse)` like opening your toolbox at the start of each work session. You always need to do this first, even if you used it yesterday!

---

### 📦 What's in Our Toolbox Today?

| Tool (from tidyverse) | What We'll Use It For Today |
|-----------------------|----------------------------|
| **dplyr** | `mutate()`, `summarize()`, `group_by()`, `count()`, plus `select()`, `filter()`, `arrange()` from Part 1 |
| **The pipe `%>%`** | Chaining all our operations together into readable pipelines |

Let's load the package:

In [2]:
# Load necessary packages
   # Load the tidyverse collection of packages
install.packages("dplyr")                     # This includes dplyr (mutate, summarize, group_by, etc.)
  library(dplyr)                   # You'll see some messages about package versions - that's normal!
    library(tidyverse)

Installing package into ‘/home/jovyan/R’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.1     ✔ readr     2.2.0
✔ ggplot2   4.0.2     ✔ stringr   1.6.0
✔ lubridate 1.9.5     ✔ tibble    3.3.1
✔ purrr     1.2.1     ✔ tidyr     1.3.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Creating Our Sample Dataset

We'll work with a **customer transactions dataset** — the kind of data you'd find at any retail or e-commerce company. This is one of the most common types of data you'll work with in business analytics.

---

### 💼 What Is Transaction Data?

Every time a customer buys something, a record is created. That record is called a **transaction**. Companies like Amazon, Walmart, Target, and every small business collect this data. It typically includes:

| Information | Why the Business Tracks It |
|-------------|---------------------------|
| **Who** bought it | Customer loyalty, targeted marketing, segmentation |
| **What** they bought | Inventory management, product recommendations |
| **How much** they paid | Revenue tracking, pricing strategy |
| **How many** they bought | Demand forecasting, bulk discount analysis |
| **When** they bought it | Seasonality, trend analysis, staffing decisions |
| **Where** they are | Regional strategy, shipping logistics, market expansion |

Our sample dataset captures all of these dimensions.

---

### 📋 Dataset Column Definitions

| Column Name | Data Type | Description | Example Values |
|------------|-----------|-------------|----------------|
| **CustomerID** | Number | Which customer made the purchase | 1, 2, 3 (can repeat — one customer, many purchases) |
| **CustomerName** | Text | Name of the customer | "Alice", "Bob", "Charlie" |
| **TransactionID** | Number | Unique identifier for each order | 1001, 1002, 1003 |
| **ProductCategory** | Text | What type of product was bought | "Electronics", "Books", "Home Goods", "Clothing" |
| **Product** | Text | Specific item purchased | "Laptop", "Novel", "Blender" |
| **UnitPrice** | Number | Price per item in dollars | 899.99, 14.99, 49.99 |
| **Quantity** | Number | How many items were purchased | 1, 2, 3 |
| **TransactionDate** | Date | When the purchase happened | "2024-03-01" |
| **Region** | Text | Geographic area of the customer | "North", "South", "East", "West" |
| **PaymentMethod** | Text | How the customer paid | "Credit Card", "Debit Card", "Cash" |

---

### 💡 Why Is This Dataset Bigger Than Lesson 3?

In Lesson 3, we used 10 rows. Today we're using **20 rows** with **8 customers** because:
- `summarize()` is more meaningful with more data to summarize
- `group_by()` needs enough rows per group to show real patterns
- `count()` is more interesting when groups have different sizes
- It's closer to what real data looks like (messy, varied, with repeat customers)

In the real world, you'd work with thousands or millions of rows — but the R code would be **exactly the same**.

---

### 🎯 HOW TO ADAPT THIS CODE FOR YOUR OWN DATA

**Template for creating your own transaction dataset:**
```r
my_data <- data.frame(
  CustomerID = c(1, 1, 2, 3),                          # Numbers, can repeat
  Product = c("Widget A", "Widget B", "Widget A", "Widget C"),  # Text in quotes
  UnitPrice = c(100, 50, 200, 75),                     # Dollar amounts
  Quantity = c(1, 2, 1, 3),                             # Whole numbers
  Date = as.Date(c("2024-01-01", "2024-01-02",
                   "2024-01-03", "2024-01-04"))          # Dates in quotes inside as.Date()
)
```

**💡 Tips:**
- Each column must have the same number of values
- CustomerID can repeat (one customer, multiple purchases)
- Text values need quotes: `"like this"`
- Numbers don't need quotes: `123`
- Dates must be wrapped in `as.Date()` to work properly

In [3]:
# Create a realistic customer transaction dataset (20 transactions, 8 customers)
customer_transactions <- data.frame(
  CustomerID = c(1, 1, 1, 2, 2, 3, 3, 3, 4, 4,
                 5, 5, 6, 6, 7, 7, 7, 8, 8, 8),
  CustomerName = c("Alice", "Alice", "Alice",
                   "Bob", "Bob",
                   "Charlie", "Charlie", "Charlie",
                   "Diana", "Diana",
                   "Ethan", "Ethan",
                   "Fiona", "Fiona",
                   "George", "George", "George",
                   "Hannah", "Hannah", "Hannah"),
  TransactionID = 1001:1020,
  ProductCategory = c("Electronics", "Books", "Clothing",
                      "Electronics", "Home Goods",
                      "Books", "Books", "Electronics",
                      "Home Goods", "Clothing",
                      "Electronics", "Clothing",
                      "Home Goods", "Books",
                      "Electronics", "Electronics", "Clothing",
                      "Books", "Home Goods", "Electronics"),
  Product = c("Laptop", "Novel", "Jacket",
              "Headphones", "Blender",
              "Textbook", "Cookbook", "Tablet",
              "Lamp", "Sneakers",
              "Smartwatch", "T-Shirt",
              "Throw Pillow", "Novel",
              "Laptop", "Headphones", "Dress Shirt",
              "Cookbook", "Coffee Maker", "Smartwatch"),
  UnitPrice = c(899.99, 14.99, 65.00,
                79.99, 49.99,
                89.95, 24.99, 349.99,
                34.99, 74.99,
                199.99, 22.50,
                28.00, 16.99,
                1099.99, 59.99, 45.00,
                24.99, 89.99, 249.99),
  Quantity = c(1, 2, 1,
               1, 1,
               1, 3, 1,
               2, 1,
               1, 3,
               2, 1,
               1, 2, 1,
               2, 1, 1),
  TransactionDate = as.Date(c("2024-03-01", "2024-03-05", "2024-03-12",
                              "2024-03-02", "2024-03-08",
                              "2024-03-03", "2024-03-10", "2024-03-15",
                              "2024-03-04", "2024-03-11",
                              "2024-03-06", "2024-03-14",
                              "2024-03-07", "2024-03-13",
                              "2024-03-09", "2024-03-16", "2024-03-20",
                              "2024-03-17", "2024-03-22", "2024-03-25")),
  Region = c("North", "North", "North",
             "South", "South",
             "East", "East", "East",
             "West", "West",
             "North", "North",
             "South", "South",
             "East", "East", "East",
             "West", "West", "West"),
  PaymentMethod = c("Credit Card", "Credit Card", "Debit Card",
                    "Debit Card", "Cash",
                    "Credit Card", "Cash", "Credit Card",
                    "Debit Card", "Credit Card",
                    "Credit Card", "Debit Card",
                    "Cash", "Cash",
                    "Credit Card", "Credit Card", "Debit Card",
                    "Debit Card", "Cash", "Credit Card")
)

# Display the complete dataset
print("Our Customer Transactions Data (20 transactions, 8 customers):")
print(customer_transactions)

[1] "Our Customer Transactions Data (20 transactions, 8 customers):"
   CustomerID CustomerName TransactionID ProductCategory      Product UnitPrice
1           1        Alice          1001     Electronics       Laptop    899.99
2           1        Alice          1002           Books        Novel     14.99
3           1        Alice          1003        Clothing       Jacket     65.00
4           2          Bob          1004     Electronics   Headphones     79.99
5           2          Bob          1005      Home Goods      Blender     49.99
6           3      Charlie          1006           Books     Textbook     89.95
7           3      Charlie          1007           Books     Cookbook     24.99
8           3      Charlie          1008     Electronics       Tablet    349.99
9           4        Diana          1009      Home Goods         Lamp     34.99
10          4        Diana          1010        Clothing     Sneakers     74.99
11          5        Ethan          1011     Electronics   Smartwatch    199.99
12          5        Ethan          1012        Clothing      T-Shirt     22.50
13          6        Fiona          1013      Home Goods Throw Pillow     28.00
14          6        Fiona          1014           Books        Novel     16.99
15          7       George          1015     Electronics       Laptop   1099.99
16          7       George          1016     Electronics   Headphones     59.99
17          7       George          1017        Clothing  Dress Shirt     45.00
18          8       Hannah          1018           Books     Cookbook     24.99
19          8       Hannah          1019      Home Goods Coffee Maker     89.99
20          8       Hannah          1020     Electronics   Smartwatch    249.99
   Quantity TransactionDate Region PaymentMethod
1         1      2024-03-01  North   Credit Card
2         2      2024-03-05  North   Credit Card
3         1      2024-03-12  North    Debit Card
4         1      2024-03-02  South    Debit Card
5         1      2024-03-08  South          Cash
6         1      2024-03-03   East   Credit Card
7         3      2024-03-10   East          Cash
8         1      2024-03-15   East   Credit Card
9         2      2024-03-04   West    Debit Card
10        1      2024-03-11   West   Credit Card
11        1      2024-03-06  North   Credit Card
12        3      2024-03-14  North    Debit Card
13        2      2024-03-07  South          Cash
14        1      2024-03-13  South          Cash
15        1      2024-03-09   East   Credit Card
16        2      2024-03-16   East   Credit Card
17        1      2024-03-20   East    Debit Card
18        2      2024-03-17   West    Debit Card
19        1      2024-03-22   West          Cash
20        1      2024-03-25   West   Credit Card

### 🔍 Exploring the Data Before We Start

Before jumping into transformations, it's good practice to understand your data first. In a real job, this is the first thing you'd do when you receive a new dataset — get a feel for its size, structure, and contents.

| What to Check | Why It Matters | R Function |
|---------------|---------------|------------|
| How many rows? | Know the size of your data | `nrow()` |
| How many columns? | Know what information is available | `ncol()` |
| What are the column names? | So you reference them correctly in code | `names()` |
| What do the first few rows look like? | Quick sanity check | `head()` |

In [4]:
# Quick data exploration - always do this with a new dataset!
cat("Number of rows (transactions):", nrow(customer_transactions), "\n")
cat("Number of columns (fields):", ncol(customer_transactions), "\n")
cat("Column names:", paste(names(customer_transactions), collapse = ", "), "\n")
cat("\nFirst 5 rows:\n")
head(customer_transactions, 5)  # head() shows the first N rows

Number of rows (transactions): 20
Number of columns (fields): 10
Column names: CustomerID, CustomerName, TransactionID, ProductCategory, Product, UnitPrice, Quantity, TransactionDate, Region, PaymentMethod

First 5 rows:

  CustomerID CustomerName TransactionID ProductCategory Product    UnitPrice
1 1          Alice        1001          Electronics     Laptop     899.99
2 1          Alice        1002          Books           Novel       14.99
3 1          Alice        1003          Clothing        Jacket      65.00
4 2          Bob          1004          Electronics     Headphones  79.99
5 2          Bob          1005          Home Goods      Blender     49.99
  Quantity TransactionDate Region PaymentMethod
1 1        2024-03-01      North  Credit Card
2 2        2024-03-05      North  Credit Card
3 1        2024-03-12      North  Debit Card
4 1        2024-03-02      South  Debit Card
5 1        2024-03-08      South  Cash

---

# ⏰ HOUR 1: Creating New Columns with mutate()

---

## 1. mutate(): Creating New Calculated Columns

### 📖 What Is mutate() and Why Does It Exist?

In almost every business dataset, the columns you *have* aren't the columns you *need*. You have `UnitPrice` and `Quantity`, but your boss wants `TotalRevenue`. You have `Amount`, but accounting needs `AmountWithTax`. You have raw numbers, but management wants categories like "High Value" and "Low Value."

**This is what `mutate()` solves.** It takes your existing columns and uses them to create new ones — just like writing a formula in a new column in Excel.

---

### 💡 The Excel Connection

If you've ever done this in Excel, you've already done what `mutate()` does:

```
Excel:  In cell D2, type =B2*C2, then drag down to fill the whole column
R:      mutate(Total = UnitPrice * Quantity)
```

The difference is that R's `mutate()` applies to **every row automatically** — no dragging needed, no chance of missing a row, and no risk of accidentally breaking the formula.

---

### 🎯 The Four Types of Mutations You'll Use in Business

| Type | What It Does | Business Example | Code Pattern |
|------|-------------|-----------------|---------------|
| **Math** | Arithmetic on columns | Total = Price × Qty | `mutate(Total = Price * Qty)` |
| **TRUE/FALSE flag** | Marks rows that meet a condition | Is this order over $500? | `mutate(BigOrder = Amount > 500)` |
| **Two-way label** | Assigns one of two labels | "Big" or "Small" | `mutate(Size = if_else(Amount > 500, "Big", "Small"))` |
| **Multi-way label** | Assigns one of several labels | "High" / "Medium" / "Low" | `mutate(Tier = case_when(...))` |

We'll learn each one step by step with examples.

---

### 🔧 mutate() Syntax Breakdown

```r
new_data <- original_data %>% mutate(NewColumn = some_calculation)
```

| Part | What It Does | Analogy |
|------|-------------|--------|
| `new_data` | Name for your result (you choose this) | The new version of your spreadsheet |
| `<-` | Assignment operator ("save this as...") | Like "Save As" in Excel |
| `original_data` | Your starting dataset | Your original spreadsheet |
| `%>%` | Pipe operator ("and then...") | Pass the data to the next step |
| `mutate()` | The function that creates new columns | "Add a formula column" |
| `NewColumn = calculation` | The name and formula | Column header = formula |

---

### ⚠️ Important: mutate() Does NOT Change Your Original Data

This is a key concept that trips up beginners. When you run `mutate()`, your original dataset is **untouched**. R creates a *new copy* with the added column. This is actually a safety feature — you can never accidentally destroy your raw data.

| What Happens | Code |
|-------------|------|
| Original data stays the same | `customer_transactions` is unchanged |
| New version has the extra column | `new_data` has everything plus the new column |
| To "save" changes permanently, overwrite | `my_data <- my_data %>% mutate(...)` |

---

Let's start with the simplest and most common use of `mutate()`:

### Example 1: Simple Math — Calculate Total Revenue Per Order

**Business question**: *"What is the total dollar amount for each transaction?"*

We have `UnitPrice` (price per item) and `Quantity` (number of items). To get the total, we multiply them. This is probably the single most common business calculation you'll ever do.

| Before mutate() | | After mutate() |
|:-:|:-:|:-:|
| UnitPrice = 899.99, Quantity = 1 | → | TotalRevenue = 899.99 |
| UnitPrice = 14.99, Quantity = 2 | → | TotalRevenue = 29.98 |
| UnitPrice = 24.99, Quantity = 3 | → | TotalRevenue = 74.97 |

**What R does behind the scenes**: It goes row by row, multiplies UnitPrice × Quantity, and puts the result in a new column called TotalRevenue.

In [5]:
# Example 1: Calculate total revenue for each transaction
transactions_with_total <- customer_transactions %>%   # Start with our data, AND THEN...
  mutate(TotalRevenue = UnitPrice * Quantity)           # Create new column: Price x Quantity

# Show just the relevant columns so it's easy to see what happened
print("Transactions with new TotalRevenue column:")
transactions_with_total %>%
  select(TransactionID, Product, UnitPrice, Quantity, TotalRevenue) %>%
  print()

[1] "Transactions with new TotalRevenue column:"
   TransactionID      Product UnitPrice Quantity TotalRevenue
1           1001       Laptop    899.99        1       899.99
2           1002        Novel     14.99        2        29.98
3           1003       Jacket     65.00        1        65.00
4           1004   Headphones     79.99        1        79.99
5           1005      Blender     49.99        1        49.99
6           1006     Textbook     89.95        1        89.95
7           1007     Cookbook     24.99        3        74.97
8           1008       Tablet    349.99        1       349.99
9           1009         Lamp     34.99        2        69.98
10          1010     Sneakers     74.99        1        74.99
11          1011   Smartwatch    199.99        1       199.99
12          1012      T-Shirt     22.50        3        67.50
13          1013 Throw Pillow     28.00        2        56.00
14          1014        Novel     16.99        1        16.99
15          1015       Laptop   1099.99        1      1099.99
16          1016   Headphones     59.99        2       119.98
17          1017  Dress Shirt     45.00        1        45.00
18          1018     Cookbook     24.99        2        49.98
19          1019 Coffee Maker     89.99        1        89.99
20          1020   Smartwatch    249.99        1       249.99

### 📖 What Just Happened?

Let's trace through what R did:

1. R took the `customer_transactions` data frame (20 rows, 10 columns)
2. For **each row**, it multiplied `UnitPrice × Quantity`
3. It stored the result in a **new column** called `TotalRevenue`
4. We saved this enhanced version as `transactions_with_total` (now has 11 columns)
5. The original `customer_transactions` is still unchanged (still 10 columns)

**Notice**: For rows where `Quantity = 1`, TotalRevenue equals UnitPrice. For rows where `Quantity > 1`, TotalRevenue is larger. That's exactly what we'd expect!

---

### 🎯 HOW TO ADAPT THIS CODE

**Template**: Replace the column names with your own.
```r
my_result <- my_data %>%
  mutate(NewColumnName = ExistingColumn1 * ExistingColumn2)
```

**Other math you can do inside mutate():**

| Operation | Symbol | Code Example |
|-----------|--------|--------------|
| Multiply | `*` | `mutate(Total = Price * Qty)` |
| Add | `+` | `mutate(FullPrice = Price + ShippingFee)` |
| Subtract | `-` | `mutate(Profit = Revenue - Cost)` |
| Divide | `/` | `mutate(PricePerUnit = Total / Qty)` |
| Percentage | `* 0.XX` | `mutate(Tax = Amount * 0.0825)` |

### Example 2: Calculating Sales Tax — Multiple New Columns at Once

**Business question**: *"Add an 8.25% Texas sales tax column and show the after-tax total."*

This is the kind of calculation you'd do constantly in real business — taxes, discounts, commissions, fees, markups. The pattern is always: take an existing number and multiply by a percentage.

**💡 Key concept**: You can create **multiple columns** in one `mutate()` call — and later columns can reference earlier ones! R processes them top to bottom.

| What We're Calculating | Formula | Code |
|-----------------------|---------|------|
| Total before tax | UnitPrice × Quantity | `TotalRevenue = UnitPrice * Quantity` |
| Sales Tax (8.25%) | Total × 0.0825 | `SalesTax = TotalRevenue * 0.0825` |
| After-Tax Total | Total + Tax | `AfterTax = TotalRevenue + SalesTax` |

In [6]:
# Example 2: Calculate sales tax and after-tax totals
transactions_with_tax <- customer_transactions %>%     # Start with our data
  mutate(
    TotalRevenue = UnitPrice * Quantity,                 # First: calculate subtotal
    SalesTax = round(TotalRevenue * 0.0825, 2),         # Second: 8.25% tax, rounded to cents
    AfterTaxTotal = round(TotalRevenue + SalesTax, 2)   # Third: add tax to total
  )                                                     # Notice: SalesTax uses TotalRevenue!
                                                        # This works because TotalRevenue was
                                                        # created first (on the line above)

print("Transactions with Sales Tax (first 8 rows):")
transactions_with_tax %>%
  select(TransactionID, Product, TotalRevenue, SalesTax, AfterTaxTotal) %>%
  head(8) %>%                                           # Show first 8 rows to save space
  print()

[1] "Transactions with Sales Tax (first 8 rows):"
  TransactionID    Product TotalRevenue SalesTax AfterTaxTotal
1          1001     Laptop       899.99    74.25        974.24
2          1002      Novel        29.98     2.47         32.45
3          1003     Jacket        65.00     5.36         70.36
4          1004 Headphones        79.99     6.60         86.59
5          1005    Blender        49.99     4.12         54.11
6          1006   Textbook        89.95     7.42         97.37
7          1007   Cookbook        74.97     6.19         81.16
8          1008     Tablet       349.99    28.87        378.86

### 📖 What Just Happened?

We created **three new columns** in one `mutate()` call. The order matters:

| Column Created | Depends On | Formula |
|---------------|------------|--------|
| `TotalRevenue` | UnitPrice, Quantity (original columns) | `UnitPrice * Quantity` |
| `SalesTax` | TotalRevenue (just created above!) | `TotalRevenue * 0.0825` |
| `AfterTaxTotal` | TotalRevenue + SalesTax (both new!) | `TotalRevenue + SalesTax` |

**Key insight**: Inside `mutate()`, columns are created **top to bottom**. `SalesTax` can use `TotalRevenue` because `TotalRevenue` was defined on the line above it. If you reversed the order, you'd get an error.

We used `round(value, 2)` to round to 2 decimal places — standard practice for dollar amounts.

### Example 3: TRUE/FALSE Flags — Marking Orders for Review

**Business question**: *"Which transactions are over $100? Flag them for the sales manager."*

A **flag** is a column that stores `TRUE` or `FALSE` for each row. It's like putting a sticky note on certain invoices that need special attention. Businesses use flags constantly:

| Business Use | Flag Logic |
|-------------|------------|
| Orders needing manager approval | Amount > $500 |
| Customers at risk of churning | Days since last purchase > 90 |
| Products running low on stock | Inventory < 10 |
| Late payments needing follow-up | Days overdue > 30 |

**How it works**: R evaluates the condition for each row and stores `TRUE` or `FALSE`.

| UnitPrice | `UnitPrice > 100` result |
|-----------|-------------------------|
| 899.99 | TRUE ✅ |
| 14.99 | FALSE ❌ |
| 349.99 | TRUE ✅ |

In [7]:
# Example 3: Create a TRUE/FALSE flag for high-value orders
transactions_flagged <- customer_transactions %>%      # Start with our data
  mutate(
    TotalRevenue = UnitPrice * Quantity,                 # Calculate total first
    IsHighValue = TotalRevenue > 100                     # TRUE if over $100, FALSE otherwise
  )

print("Transactions with High-Value Flag:")
transactions_flagged %>%
  select(TransactionID, Product, TotalRevenue, IsHighValue) %>%
  print()

# Bonus: Count how many are high value vs. not
# sum() on TRUE/FALSE counts the TRUEs (TRUE = 1, FALSE = 0)
cat("\nHigh-value transactions (> $100):", sum(transactions_flagged$IsHighValue),
    "out of", nrow(transactions_flagged), "total\n")

[1] "Transactions with High-Value Flag:"
   TransactionID      Product TotalRevenue IsHighValue
1           1001       Laptop       899.99        TRUE
2           1002        Novel        29.98       FALSE
3           1003       Jacket        65.00       FALSE
4           1004   Headphones        79.99       FALSE
5           1005      Blender        49.99       FALSE
6           1006     Textbook        89.95       FALSE
7           1007     Cookbook        74.97       FALSE
8           1008       Tablet       349.99        TRUE
9           1009         Lamp        69.98       FALSE
10          1010     Sneakers        74.99       FALSE
11          1011   Smartwatch       199.99        TRUE
12          1012      T-Shirt        67.50       FALSE
13          1013 Throw Pillow        56.00       FALSE
14          1014        Novel        16.99       FALSE
15          1015       Laptop      1099.99        TRUE
16          1016   Headphones       119.98        TRUE
17          1017  Dress Shirt        45.00       FALSE
18          1018     Cookbook        49.98       FALSE
19          1019 Coffee Maker        89.99       FALSE
20          1020   Smartwatch       249.99        TRUE

High-value transactions (> $100): 6 out of 20 total

### Example 4: Two-Way Labels with if_else()

**Business question**: *"Label each order as 'Premium' or 'Standard' based on whether the total is over $100."*

TRUE/FALSE flags are useful for calculations, but they aren't great for reports. Your manager doesn't want to see `TRUE` — they want to see `"Premium"`. The `if_else()` function lets you assign **text labels** instead.

---

### 🔧 if_else() Syntax Breakdown

```r
if_else(condition, value_if_TRUE, value_if_FALSE)
```

| Part | What It Means | Example |
|------|-------------|--------|
| `condition` | The test to apply to each row | `TotalRevenue > 100` |
| `value_if_TRUE` | Label when condition IS met | `"Premium"` |
| `value_if_FALSE` | Label when condition is NOT met | `"Standard"` |

**💡 Read it like English**: "IF the total is over 100, THEN call it Premium, ELSE call it Standard."

In [9]:
# Example 4: Two-way labels with if_else()
transactions_labeled <- customer_transactions %>%      # Start with our data
  mutate(
    TotalRevenue = UnitPrice * Quantity,                 # Calculate total
    OrderTier = if_else(TotalRevenue > 100,              # IF total > $100
                        "Premium",                       #   THEN label "Premium"
                        "Standard")                      #   ELSE label "Standard"
  )

print("Transactions with Order Tier Labels:")
transactions_labeled %>%
  select(TransactionID, Product, TotalRevenue, OrderTier) %>%
  print()

[1] "Transactions with Order Tier Labels:"
   TransactionID      Product TotalRevenue OrderTier
1           1001       Laptop       899.99   Premium
2           1002        Novel        29.98  Standard
3           1003       Jacket        65.00  Standard
4           1004   Headphones        79.99  Standard
5           1005      Blender        49.99  Standard
6           1006     Textbook        89.95  Standard
7           1007     Cookbook        74.97  Standard
8           1008       Tablet       349.99   Premium
9           1009         Lamp        69.98  Standard
10          1010     Sneakers        74.99  Standard
11          1011   Smartwatch       199.99   Premium
12          1012      T-Shirt        67.50  Standard
13          1013 Throw Pillow        56.00  Standard
14          1014        Novel        16.99  Standard
15          1015       Laptop      1099.99   Premium
16          1016   Headphones       119.98   Premium
17          1017  Dress Shirt        45.00  Standard
18          1018     Cookbook        49.98  Standard
19          1019 Coffee Maker        89.99  Standard
20          1020   Smartwatch       249.99   Premium

### Example 5: Multi-Way Labels with case_when()

**Business question**: *"Classify each order into 'High', 'Medium', or 'Low' value tiers."*

`if_else()` only gives you two options. But what if you need three, four, or more categories? That's where `case_when()` comes in. It works like a series of IF-ELSE statements that R checks **from top to bottom**.

---

### 🔧 case_when() Syntax Breakdown

```r
case_when(
  condition1 ~ "Label 1",    # Check this first
  condition2 ~ "Label 2",    # If first didn't match, check this
  TRUE       ~ "Default"     # Everything else gets this label
)
```

| Part | What It Means |
|------|-------------|  
| `condition1` | The first test (e.g., `Amount > 200`) |
| `~` | The tilde means "then assign this label" (think of it as an arrow →) |
| `"Label 1"` | The text label to assign (always in quotes) |
| `,` | Comma separates each condition-label pair |
| `TRUE ~ "Default"` | Catch-all for rows that didn't match above (like "else" in Excel IF) |

---

### ⚠️ Order Matters in case_when()!

R checks conditions **from top to bottom** and stops at the **first match**. Put your most restrictive condition first:

| Order | Code | A $300 order gets... |
|-------|------|---------------------|
| ✅ Correct | `> 200 ~ "High"` first, then `> 50 ~ "Medium"` | **"High"** (correct!) |
| ❌ Wrong | `> 50 ~ "Medium"` first, then `> 200 ~ "High"` | **"Medium"** (wrong! $300 IS > 50, so it matches too early) |

**Rule of thumb**: Start with the biggest/most restrictive number, work down, and always end with `TRUE ~ "Default"`.

In [10]:
# Example 5: Multi-way labels with case_when()
transactions_tiered <- customer_transactions %>%       # Start with our data
  mutate(
    TotalRevenue = UnitPrice * Quantity,                 # Calculate total
    ValueTier = case_when(
      TotalRevenue > 200 ~ "High",                       # Over $200 = High (check first!)
      TotalRevenue > 50  ~ "Medium",                     # $50.01 to $200 = Medium
      TRUE               ~ "Low"                         # $50 and under = Low (catch-all)
    )
  )

print("Transactions with Value Tiers:")
transactions_tiered %>%
  select(TransactionID, Product, TotalRevenue, ValueTier) %>%
  print()

[1] "Transactions with Value Tiers:"
   TransactionID      Product TotalRevenue ValueTier
1           1001       Laptop       899.99      High
2           1002        Novel        29.98       Low
3           1003       Jacket        65.00    Medium
4           1004   Headphones        79.99    Medium
5           1005      Blender        49.99       Low
6           1006     Textbook        89.95    Medium
7           1007     Cookbook        74.97    Medium
8           1008       Tablet       349.99      High
9           1009         Lamp        69.98    Medium
10          1010     Sneakers        74.99    Medium
11          1011   Smartwatch       199.99    Medium
12          1012      T-Shirt        67.50    Medium
13          1013 Throw Pillow        56.00    Medium
14          1014        Novel        16.99       Low
15          1015       Laptop      1099.99      High
16          1016   Headphones       119.98    Medium
17          1017  Dress Shirt        45.00       Low
18          1018     Cookbook        49.98       Low
19          1019 Coffee Maker        89.99    Medium
20          1020   Smartwatch       249.99      High

### 📖 Let's Trace Through a Few Rows

To make sure you understand how `case_when()` decides, let's walk through the logic for three different orders:

| Row | TotalRevenue | Is it > 200? | Is it > 50? | Hits TRUE? | Result |
|-----|-------------|-------------|------------|-----------|--------|
| Laptop ($899.99) | 899.99 | ✅ YES → stops here | — | — | **"High"** |
| Jacket ($65.00) | 65.00 | ❌ no | ✅ YES → stops here | — | **"Medium"** |
| Novel ($14.99 × 2) | 29.98 | ❌ no | ❌ no | ✅ catches it | **"Low"** |

R checks from the top down and assigns the **first match**. The `TRUE ~` at the bottom catches everything that didn't match any condition above it.

### Example 6: The Complete mutate() — Building an Enhanced Transaction Table

**Business question**: *"Give me a complete enhanced view of each transaction: total revenue, sales tax, after-tax total, and a value tier."*

This is what a real analyst would build — combining all the `mutate()` patterns into one call.

In [11]:
# Example 6: Build a complete enhanced transaction table
enhanced_transactions <- customer_transactions %>%     # Start with our data
  mutate(
    TotalRevenue = UnitPrice * Quantity,                 # Total order amount
    SalesTax = round(TotalRevenue * 0.0825, 2),         # 8.25% Texas sales tax
    AfterTaxTotal = round(TotalRevenue + SalesTax, 2),  # Grand total with tax
    IsHighValue = TotalRevenue > 100,                    # TRUE/FALSE flag
    ValueTier = case_when(                               # Category label
      TotalRevenue > 200 ~ "High",
      TotalRevenue > 50  ~ "Medium",
      TRUE               ~ "Low"
    )
  )

# Show the key columns from our enhanced data
print("Complete Enhanced Transaction Data:")
enhanced_transactions %>%
  select(TransactionID, CustomerName, Product, TotalRevenue,
         SalesTax, AfterTaxTotal, ValueTier) %>%
  print()

[1] "Complete Enhanced Transaction Data:"
   TransactionID CustomerName      Product TotalRevenue SalesTax AfterTaxTotal
1           1001        Alice       Laptop       899.99    74.25        974.24
2           1002        Alice        Novel        29.98     2.47         32.45
3           1003        Alice       Jacket        65.00     5.36         70.36
4           1004          Bob   Headphones        79.99     6.60         86.59
5           1005          Bob      Blender        49.99     4.12         54.11
6           1006      Charlie     Textbook        89.95     7.42         97.37
7           1007      Charlie     Cookbook        74.97     6.19         81.16
8           1008      Charlie       Tablet       349.99    28.87        378.86
9           1009        Diana         Lamp        69.98     5.77         75.75
10          1010        Diana     Sneakers        74.99     6.19         81.18
11          1011        Ethan   Smartwatch       199.99    16.50        216.49
12          1012        Ethan      T-Shirt        67.50     5.57         73.07
13          1013        Fiona Throw Pillow        56.00     4.62         60.62
14          1014        Fiona        Novel        16.99     1.40         18.39
15          1015       George       Laptop      1099.99    90.75       1190.74
16          1016       George   Headphones       119.98     9.90        129.88
17          1017       George  Dress Shirt        45.00     3.71         48.71
18          1018       Hannah     Cookbook        49.98     4.12         54.10
19          1019       Hannah Coffee Maker        89.99     7.42         97.41
20          1020       Hannah   Smartwatch       249.99    20.62        270.61
   ValueTier
1       High
2        Low
3     Medium
4     Medium
5        Low
6     Medium
7     Medium
8       High
9     Medium
10    Medium
11    Medium
12    Medium
13    Medium
14       Low
15      High
16    Medium
17       Low
18       Low
19    Medium
20      High

### ✏️ Try It Yourself!

Practice `mutate()` with these exercises. Use the `customer_transactions` data.

1. Create a column called `DoublePrice` that doubles the `UnitPrice`
2. Create a column called `DiscountPrice` that gives a 15% discount on `UnitPrice` (hint: `UnitPrice * 0.85`)
3. Create a column called `BulkOrder` that is `TRUE` if `Quantity > 1`
4. Create a column called `PriceBracket` using `case_when()`: "Expensive" if UnitPrice > 100, "Moderate" if > 30, "Budget" otherwise

**💡 Starter code:**
```r
customer_transactions %>%
  mutate(
    DoublePrice = ___,
    DiscountPrice = ___,
    BulkOrder = ___,
    PriceBracket = case_when(___)
  ) %>%
  select(Product, UnitPrice, DoublePrice, DiscountPrice, Quantity, BulkOrder, PriceBracket)
```

In [19]:
# YOUR PRACTICE SPACE - Try the exercises above!
# Uncomment and fill in the blanks:

 customer_transactions %>%
  mutate(
  DoublePrice = UnitPrice * 2,
  DiscountPrice = UnitPrice *0.9,
 BulkOrder = Quantity > 1,
 PriceBracket = case_when(
    UnitPrice > 100 ~ "Expensive",
    UnitPrice > 50 ~ "Moderate",
        TRUE ~ "Budget"
 ) %>%
  select(Product, UnitPrice, DoublePrice, DiscountPrice, Quantity, BulkOrder, PriceBracket)

ERROR: Error in parse(text = input): <text>:15:0: unexpected end of input
13:  ) %>%
14:   select(Product, UnitPrice, DoublePrice, DiscountPrice, Quantity, BulkOrder, PriceBracket)
   ^

### 🎯 mutate() Quick Reference

| Pattern | Code | When to Use |
|---------|------|------------|
| Simple math | `mutate(Total = Price * Qty)` | Totals, percentages, rates |
| Rounding | `mutate(Rounded = round(Amount, 2))` | Cleaning up decimal places |
| TRUE/FALSE | `mutate(Flag = Amount > 100)` | Marking rows for filtering later |
| Two labels | `mutate(L = if_else(Amt > 100, "High", "Low"))` | Simple yes/no categories |
| Multiple labels | `mutate(Tier = case_when(Amt > 200 ~ "A", ...))` | Three or more categories |
| Multiple columns | `mutate(Col1 = ..., Col2 = ..., Col3 = ...)` | Building several calculations at once |

---

# ⏰ HOUR 2: Summarizing and Grouping Data

---

Now we shift from adding columns to **collapsing data into summaries**. This is where your data stops being a list of individual transactions and starts becoming a **business report** that executives can act on.

## 2. summarize(): Getting the Big Picture Numbers

### 📖 What Is summarize() and Why Does It Exist?

Your VP doesn't want to see 20 rows of transactions. They want to hear: *"Total revenue was $X, average order was $Y, and we served Z customers."* That's **one row** of summary numbers — and that's exactly what `summarize()` creates.

The `summarize()` function takes your entire dataset and **collapses it into a single row** of aggregate numbers. Think of it as the **totals row at the bottom of a spreadsheet**.

---

### 💡 The Excel Connection

| What You'd Do in Excel | What You'd Write in R |
|-----------------------|----------------------|
| `=SUM(B2:B21)` in a cell below the data | `summarize(Total = sum(Amount))` |
| `=AVERAGE(B2:B21)` in another cell | Add `Avg = mean(Amount)` |
| `=COUNTA(A2:A21)` in another cell | Add `Count = n())` |
| Each formula lives in a separate cell | All metrics in one `summarize()` call |

---

### 📋 Summary Functions You'll Use Constantly

| Function | What It Calculates | Excel Equivalent | Example |
|----------|-------------------|-----------------|--------|
| `sum()` | Total of all values | `=SUM()` | `sum(Amount)` → total revenue |
| `mean()` | Average (sum ÷ count) | `=AVERAGE()` | `mean(Amount)` → average order |
| `median()` | Middle value when sorted | `=MEDIAN()` | `median(Amount)` → typical order |
| `n()` | Count of rows | `=COUNTA()` | `n()` → number of transactions |
| `n_distinct()` | Count of unique values | `=COUNTUNIQUE()` | `n_distinct(CustomerID)` → unique customers |
| `min()` | Smallest value | `=MIN()` | `min(Amount)` → smallest order |
| `max()` | Largest value | `=MAX()` | `max(Amount)` → biggest order |
| `sd()` | Standard deviation | `=STDEV()` | `sd(Amount)` → spread of orders |

---

### 📊 mean() vs. median() — A Business Analyst Must Know the Difference

This comes up constantly in business reporting:

| Function | How It Works | Best When... | Example |
|----------|-------------|-------------|--------|
| `mean()` | Adds everything, divides by count | Data is evenly spread | Average monthly sales |
| `median()` | Finds the middle value | Data has outliers/extremes | Typical home price, typical salary |

**Why it matters**: If 9 employees earn $50K and 1 CEO earns $5M:
- `mean()` salary = $545K — misleading, nobody actually earns this!
- `median()` salary = $50K — accurate for a "typical" employee

**Best practice**: Report both. When they differ a lot, that tells your audience there are outliers pulling the average up or down.

---

### 🔧 summarize() Syntax Breakdown

```r
result <- my_data %>% summarize(MetricName = function(column))
```

| Part | What It Does | Analogy |
|------|-------------|--------|
| `result` | Name for your output | Your one-row executive report |
| `my_data %>%` | Start with your full dataset | All 20 rows of transactions |
| `summarize()` | Collapse all rows into one summary row | Like pressing "AutoSum" in Excel |
| `MetricName = ` | Name you give each metric | The column header in your report |
| `function(column)` | The math to do | Which summary function to use |

**💡 Remember**: `summarize()` without `group_by()` always returns **one single row** — the summary of your entire dataset.

---

### 🎯 HOW TO ADAPT THIS CODE

**Template for a basic business summary:**
```r
my_summary <- my_data %>%
  summarize(
    TotalRevenue = sum(amount_column),
    AvgOrder = round(mean(amount_column), 2),
    MedianOrder = median(amount_column),
    OrderCount = n(),
    UniqueCustomers = n_distinct(customer_id_column)
  )
```

Let's build a summary:

In [ ]:
# Overall business summary - collapses 20 rows into 1
overall_summary <- customer_transactions %>%           # Start with all 20 transactions
  mutate(TotalRevenue = UnitPrice * Quantity) %>%       # First calculate each order's total
  summarize(
    Total_Revenue = round(sum(TotalRevenue), 2),         # Sum of ALL order totals
    Avg_Order = round(mean(TotalRevenue), 2),            # Average order value
    Median_Order = median(TotalRevenue),                  # Typical order value
    Total_Orders = n(),                                  # Count of transactions (rows)
    Unique_Customers = n_distinct(CustomerID),           # Count of unique customer IDs
    Total_Items_Sold = sum(Quantity),                     # Total units sold
    Smallest_Order = min(TotalRevenue),                   # Lowest order total
    Largest_Order = max(TotalRevenue)                     # Highest order total
  )

print("Overall Business Summary (20 transactions collapsed to 1 row):")
print(overall_summary)

### 📖 Reading the Output

We went from **20 rows** of transaction data to **1 row** of key metrics. Here's what each tells your manager:

| Metric | What It Tells You | Why It Matters |
|--------|------------------|---------------|
| **Total_Revenue** | All money that came in | Headline number for any report |
| **Avg_Order** | Average dollars per transaction | Trend tracking — going up or down? |
| **Median_Order** | The "typical" order size | More reliable than mean when outliers exist |
| **Total_Orders** | How many transactions happened | Volume metric |
| **Unique_Customers** | How many different people bought | Customer reach metric |
| **Total_Items_Sold** | Total units moved | Inventory and demand metric |
| **Smallest / Largest** | Range of order sizes | Shows business diversity |

**Notice**: Compare mean and median. If they differ a lot, it means outliers (like expensive laptops) are pulling the average. That's valuable context for your audience.

This one row is exactly what you'd put in a weekly email update, a PowerPoint slide, or the top of a Tableau dashboard.

## 3. group_by() + summarize(): The Pivot Table of R

### 📖 What Is group_by() and Why Is It So Important?

The `summarize()` above gave us **one row** for the entire dataset. But what if you want summaries for **each region**, or **each product category**, or **each customer** — all at once?

That's what `group_by()` does. **It is R's version of an Excel Pivot Table.** It splits your data into groups, then `summarize()` calculates stats for each group separately.

This is arguably **the single most important skill in business analytics**. Almost every business report involves breaking down numbers by category.

---

### 💡 The Excel Pivot Table Connection

| In Excel Pivot Table... | In R... |
|------------------------|--------|
| Drag "Region" to the **Rows** area | `group_by(Region)` |
| Drag "Amount" to **Values**, set to SUM | `summarize(Total = sum(Amount))` |
| Drag "Amount" to Values again, set to AVERAGE | Add `Avg = mean(Amount)` |
| **Result**: one row per Region with calculated metrics | Exactly the same! |

---

### 🔧 How group_by() + summarize() Works — Step by Step

```
Step 1: group_by(Region)  — "Split the data into piles"
┌─────────────────────────────────────┐
│  All 20 transactions (mixed)        │
└─────────────────────────────────────┘
         ↓ Split into 4 piles ↓
┌──────────┐ ┌──────────┐ ┌──────────┐ ┌──────────┐
│  North   │ │  South   │ │  East    │ │  West    │
│  5 rows  │ │  4 rows  │ │  6 rows  │ │  5 rows  │
└──────────┘ └──────────┘ └──────────┘ └──────────┘

Step 2: summarize(Total = sum(Amount))  — "Add up each pile"
┌──────────┐ ┌──────────┐ ┌──────────┐ ┌──────────┐
│North:$XXX│ │South:$XXX│ │East:$XXX │ │West:$XXX │
└──────────┘ └──────────┘ └──────────┘ └──────────┘
         ↓ Combine into one table ↓
┌────────────────────────────┐
│  Region  │  Total          │
│  North   │  $XXX           │
│  South   │  $XXX           │
│  East    │  $XXX           │
│  West    │  $XXX           │
└────────────────────────────┘
```

This "split → apply → combine" pattern is the foundation of almost all business analysis.

---

### ⚠️ Always Use `.groups = 'drop'`

After `group_by() + summarize()`, R keeps your data "grouped" behind the scenes. This can cause unexpected behavior if you do more operations later. Always add `.groups = 'drop'` to clean up.

| Code | What Happens |
|------|-------------|
| `summarize(..., .groups = 'drop')` | ✅ Clean result, safe for further analysis |
| `summarize(...)` without it | ⚠️ Data stays grouped — later operations may behave strangely |

**Rule of thumb**: Always include `.groups = 'drop'`. Make it a habit.

---

### 🎯 HOW TO ADAPT THIS CODE

**Template for one grouping column:**
```r
my_report <- my_data %>%
  group_by(category_column) %>%
  summarize(
    Total = sum(amount_column),
    Average = round(mean(amount_column), 2),
    Count = n(),
    .groups = 'drop'
  ) %>%
  arrange(desc(Total))
```

**Template for two grouping columns:**
```r
my_report <- my_data %>%
  group_by(column1, column2) %>%
  summarize(Total = sum(amount_column), .groups = 'drop')
```

Let's see it in action:

### Example 1: Sales by Product Category

**Business question**: *"How do our product categories compare in revenue, volume, and average order size?"*

This is one of the most common business reports — comparing performance across product lines.

In [20]:
# Group by Product Category - like an Excel Pivot Table!
sales_by_category <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(ProductCategory) %>%
  summarize(
    Total_Revenue = round(sum(TotalRevenue), 2),
    Avg_Order = round(mean(TotalRevenue), 2),
    Num_Orders = n(),
    Num_Customers = n_distinct(CustomerID),
    .groups = 'drop'
  ) %>%
  arrange(desc(Total_Revenue))

print("Sales Summary by Product Category:")
print(sales_by_category)

[1] "Sales Summary by Product Category:"
# A tibble: 4 × 5
  ProductCategory Total_Revenue Avg_Order Num_Orders Num_Customers
  <chr>                   <dbl>     <dbl>      <int>         <int>
1 Electronics             3000.     429.           7             6
2 Home Goods               266.      66.5          4             4
3 Books                    262.      52.4          5             4
4 Clothing                 252.      63.1          4             4

### Example 2: Sales by Region

**Business question**: *"How does each geographic region perform? Where should we invest more?"*

Regional analysis drives decisions about store locations, marketing spend, hiring, and expansion.

In [21]:
# Group by Region
sales_by_region <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(Region) %>%
  summarize(
    Total_Revenue = round(sum(TotalRevenue), 2),
    Avg_Order = round(mean(TotalRevenue), 2),
    Num_Orders = n(),
    Num_Customers = n_distinct(CustomerID),
    .groups = 'drop'
  ) %>%
  arrange(desc(Total_Revenue))

print("Sales Summary by Region:")
print(sales_by_region)

[1] "Sales Summary by Region:"
# A tibble: 4 × 5
  Region Total_Revenue Avg_Order Num_Orders Num_Customers
  <chr>          <dbl>     <dbl>      <int>         <int>
1 East           1780.     297.           6             2
2 North          1262.     252.           5             2
3 West            535.     107.           5             2
4 South           203.      50.7          4             2

### Example 3: Customer-Level Analysis — Finding Your Best Customers

**Business question**: *"Who are our best customers? How much has each one spent total?"*

Understanding individual customer behavior is the foundation of CRM (Customer Relationship Management), loyalty programs, and targeted marketing.

In [22]:
# Group by Customer - build customer spending profiles
spending_by_customer <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(CustomerID, CustomerName) %>%
  summarize(
    Total_Spent = round(sum(TotalRevenue), 2),
    Num_Orders = n(),
    Avg_Order = round(mean(TotalRevenue), 2),
    Num_Categories = n_distinct(ProductCategory),
    .groups = 'drop'
  ) %>%
  arrange(desc(Total_Spent))

print("Customer Spending Profiles (ranked by total):")
print(spending_by_customer)

[1] "Customer Spending Profiles (ranked by total):"
# A tibble: 8 × 6
  CustomerID CustomerName Total_Spent Num_Orders Avg_Order Num_Categories
       <dbl> <chr>              <dbl>      <int>     <dbl>          <int>
1          7 George            1265.           3     422.               2
2          1 Alice              995.           3     332.               3
3          3 Charlie            515.           3     172.               2
4          8 Hannah             390.           3     130.               3
5          5 Ethan              267.           2     134.               2
6          4 Diana              145.           2      72.5              2
7          2 Bob                130.           2      65.0              2
8          6 Fiona               73.0          2      36.5              2

### 📖 What This Tells You About Your Customers

| Metric | If It's High... | Business Action |
|--------|----------------|----------------|
| **Total_Spent** | VIP customer | Give them loyalty perks, don't lose them |
| **Num_Orders** | Frequent buyer | Offer subscriptions or auto-reorder |
| **Avg_Order** | Big-ticket buyer | Target for premium product launches |
| **Num_Categories** | Cross-shopper | Very engaged — keep offering variety |

| Metric | If It's Low... | Business Action |
|--------|----------------|----------------|
| **Total_Spent** | Light spender | Try promotions or incentives |
| **Num_Orders** | One-time buyer | Send a follow-up offer to bring them back |
| **Num_Categories** | Single-category | Cross-sell — recommend other products |

### Example 4: Grouping by Two Columns

**Business question**: *"What are our sales by region AND product category?"*

Sometimes one grouping isn't detailed enough. Pass **two columns** to `group_by()` for a more granular breakdown.

In [23]:
# Group by BOTH Region and ProductCategory
sales_by_region_category <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(Region, ProductCategory) %>%
  summarize(
    Revenue = round(sum(TotalRevenue), 2),
    Orders = n(),
    .groups = 'drop'
  ) %>%
  arrange(Region, desc(Revenue))

print("Sales by Region and Product Category:")
print(sales_by_region_category)

[1] "Sales by Region and Product Category:"
# A tibble: 13 × 4
   Region ProductCategory Revenue Orders
   <chr>  <chr>             <dbl>  <int>
 1 East   Electronics      1570.       3
 2 East   Books             165.       2
 3 East   Clothing           45        1
 4 North  Electronics      1100.       2
 5 North  Clothing          132.       2
 6 North  Books              30.0      1
 7 South  Home Goods        106.       2
 8 South  Electronics        80.0      1
 9 South  Books              17.0      1
10 West   Electronics       250.       1
11 West   Home Goods        160.       2
12 West   Clothing           75.0      1
13 West   Books              50.0      1

### ✏️ Try It Yourself!

Practice `group_by() + summarize()`:

1. Get the total revenue and order count **by PaymentMethod**
2. Find the average UnitPrice **by ProductCategory**
3. Count the number of transactions **by Region and PaymentMethod** (two grouping columns)

**💡 Starter code for Exercise 1:**
```r
customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(PaymentMethod) %>%
  summarize(
    Revenue = sum(Total Revenue),
    Orders = n(),
    .groups = 'drop'
  ) %>%
  arrange(desc(Revenue))
```

In [25]:
# YOUR PRACTICE SPACE - Try the group_by exercises!
customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(PaymentMethod) %>%
  summarize(
    Total_Revenue = round(sum(TotalRevenue), 2),
    Avg_Order = round(mean(TotalRevenue), 2),
    Num_Orders = n(),
    Num_Customers = n_distinct(CustomerID),
    .groups = 'drop'
  ) %>%
  arrange(desc(Total_Revenue))

  PaymentMethod Total_Revenue Avg_Order Num_Orders Num_Customers
1 Credit Card   3114.85       346.09    9          6
2 Debit Card     377.45        62.91    6          6
3 Cash           287.94        57.59    5          4

## 4. count(): Quick Frequency Counts

### 📖 What Is count()?

`count()` is a shortcut that answers: **"How many of each?"** It groups your data and counts rows per group.

You *could* do this with `group_by() + summarize(n = n())`, but `count()` is cleaner for simple counting.

---

### 💡 count() vs. group_by() + summarize()

| Situation | Use This | Why |
|-----------|----------|-----|
| You ONLY need a count | `count()` | Less typing, cleaner |
| You need count AND other metrics | `group_by() + summarize()` | `count()` can only count |

These two produce the **exact same result**:
```r
# Short way:
data %>% count(Region, sort = TRUE)

# Long way (same result):
data %>% group_by(Region) %>% summarize(n = n(), .groups = 'drop') %>% arrange(desc(n))
```

---

### 🔧 count() Syntax

```r
my_data %>% count(column_name, sort = TRUE)
```

| Part | What It Does |
|------|-------------|
| `count()` | Groups by the column and counts rows |
| `column_name` | Which column to group by |
| `sort = TRUE` | Optional: highest count first (always include this) |
| Output column `n` | The count for each group (automatic name) |

In [26]:
# Example 1: Count orders per product category
print("Orders per Product Category:")
customer_transactions %>%
  count(ProductCategory, sort = TRUE) %>%
  print()

# Example 2: Count orders per region
cat("\n")
print("Orders per Region:")
customer_transactions %>%
  count(Region, sort = TRUE) %>%
  print()

# Example 3: Count with percentages (the business-ready version)
cat("\n")
print("Payment Method Breakdown with Percentages:")
customer_transactions %>%
  count(PaymentMethod, sort = TRUE) %>%
  mutate(Pct = round((n / sum(n)) * 100, 1)) %>%
  print()

# Example 4: Cross-tab - count by two columns
cat("\n")
print("Orders by Region and Product Category:")
customer_transactions %>%
  count(Region, ProductCategory, sort = TRUE) %>%
  print()

[1] "Orders per Product Category:"
  ProductCategory n
1     Electronics 7
2           Books 5
3        Clothing 4
4      Home Goods 4

[1] "Orders per Region:"
  Region n
1   East 6
2  North 5
3   West 5
4  South 4

[1] "Payment Method Breakdown with Percentages:"
  PaymentMethod n Pct
1   Credit Card 9  45
2    Debit Card 6  30
3          Cash 5  25

[1] "Orders by Region and Product Category:"
   Region ProductCategory n
1    East     Electronics 3
2    East           Books 2
3   North        Clothing 2
4   North     Electronics 2
5   South      Home Goods 2
6    West      Home Goods 2
7    East        Clothing 1
8   North           Books 1
9   South           Books 1
10  South     Electronics 1
11   West           Books 1
12   West        Clothing 1
13   West     Electronics 1

### 📖 Understanding the Percentage Pattern

The formula `round((n / sum(n)) * 100, 1)` will come up over and over. Let's break it down:

| Step | What It Does | Example (if Credit Card has n=8, total=20) |
|------|-------------|---------------------------------------------|
| `n` | The count for this row | 8 |
| `sum(n)` | Total count across ALL rows | 20 |
| `n / sum(n)` | Proportion (decimal) | 8/20 = 0.40 |
| `* 100` | Convert to percentage | 0.40 × 100 = 40.0 |
| `round(..., 1)` | Round to 1 decimal place | 40.0% |

This same pattern works for revenue share, market share, or any "percent of total" calculation. Memorize it!

## 5. Combining Everything: Real Business Pipelines

### 📖 This Is Where It All Comes Together

In real analytics, you chain functions into **pipelines** that go from raw data to finished reports.

### 🎯 The Standard Business Pipeline

```
📦 Raw Data
    ↓  filter()      — Keep only the rows you need
    ↓  mutate()      — Add calculated columns
    ↓  group_by()    — Split into groups
    ↓  summarize()   — Calculate metrics per group
    ↓  mutate()      — Add percentages to the summary
    ↓  arrange()     — Sort the final result
📋 Finished Report
```

### 🎯 HOW TO ADAPT THIS CODE

**Template for a complete KPI report:**
```r
my_report <- my_data %>%
  filter(date_column >= "2024-01-01") %>%        # Optional: filter time period
  mutate(Total = price_col * qty_col) %>%         # Calculate
  group_by(category_column) %>%                   # Group
  summarize(                                      # Summarize per group
    Revenue = sum(Total),
    Orders = n(),
    Avg_Order = round(mean(Total), 2),
    Customers = n_distinct(customer_id_col),
    .groups = 'drop'
  ) %>%
  mutate(Pct_Revenue = round(                     # Add percentages
    (Revenue / sum(Revenue)) * 100, 1
  )) %>%
  arrange(desc(Revenue))                          # Sort
```

### Example 1: Regional KPI Report with Revenue Share

**Business question**: *"Total revenue, order count, average order, customer count, and revenue percentage by region — sorted best to worst."*

In [27]:
# Regional KPI Report - a complete pipeline
regional_kpis <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(Region) %>%
  summarize(
    Revenue = round(sum(TotalRevenue), 2),
    Orders = n(),
    Avg_Order = round(mean(TotalRevenue), 2),
    Customers = n_distinct(CustomerID),
    .groups = 'drop'
  ) %>%
  mutate(
    Revenue_Share = round((Revenue / sum(Revenue)) * 100, 1)
  ) %>%
  arrange(desc(Revenue))

print("Regional KPI Report:")
print(regional_kpis)

[1] "Regional KPI Report:"
# A tibble: 4 × 6
  Region Revenue Orders Avg_Order Customers Revenue_Share
  <chr>    <dbl>  <int>     <dbl>     <int>         <dbl>
1 East     1780.      6     297.          2          47.1
2 North    1262.      5     252.          2          33.4
3 West      535.      5     107.          2          14.2
4 South     203.      4      50.7         2           5.4

### Example 2: Customer Segmentation Report

**Business question**: *"Classify our customers into Gold/Silver/Bronze value tiers based on total spending."*

Customer segmentation tells marketing who to target, sales who to prioritize, and management where to invest.

In [28]:
# Customer Segmentation Report
customer_segments <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(CustomerID, CustomerName) %>%
  summarize(
    Total_Spent = round(sum(TotalRevenue), 2),
    Num_Orders = n(),
    Avg_Order = round(mean(TotalRevenue), 2),
    Num_Categories = n_distinct(ProductCategory),
    .groups = 'drop'
  ) %>%
  mutate(
    Value_Tier = case_when(
      Total_Spent >= 500 ~ "Gold",
      Total_Spent >= 200 ~ "Silver",
      TRUE               ~ "Bronze"
    )
  ) %>%
  arrange(desc(Total_Spent))

print("Customer Segmentation Report:")
print(customer_segments)

# Summary: how many customers in each tier?
cat("\nSegment Distribution:\n")
customer_segments %>%
  count(Value_Tier) %>%
  mutate(Pct = round((n / sum(n)) * 100, 1)) %>%
  print()

[1] "Customer Segmentation Report:"
# A tibble: 8 × 7
  CustomerID CustomerName Total_Spent Num_Orders Avg_Order Num_Categories
       <dbl> <chr>              <dbl>      <int>     <dbl>          <int>
1          7 George            1265.           3     422.               2
2          1 Alice              995.           3     332.               3
3          3 Charlie            515.           3     172.               2
4          8 Hannah             390.           3     130.               3
5          5 Ethan              267.           2     134.               2
6          4 Diana              145.           2      72.5              2
7          2 Bob                130.           2      65.0              2
8          6 Fiona               73.0          2      36.5              2
# ℹ 1 more variable: Value_Tier <chr>

Segment Distribution:
# A tibble: 3 × 3
  Value_Tier     n   Pct
  <chr>      <int> <dbl>
1 Bronze         3  37.5
2 Gold           3  37.5
3 Silver         2  25

### Example 3: Product Performance Rankings

**Business question**: *"Rank product categories by revenue with share percentages."*

In [29]:
# Product Performance Report with rankings
product_performance <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(ProductCategory) %>%
  summarize(
    Revenue = round(sum(TotalRevenue), 2),
    Orders = n(),
    Avg_Order = round(mean(TotalRevenue), 2),
    Customers = n_distinct(CustomerID),
    Avg_Qty = round(mean(Quantity), 1),
    .groups = 'drop'
  ) %>%
  mutate(
    Revenue_Share = round((Revenue / sum(Revenue)) * 100, 1),
    Rank = rank(desc(Revenue))
  ) %>%
  arrange(Rank)

print("Product Category Performance Report:")
print(product_performance)

[1] "Product Category Performance Report:"
# A tibble: 4 × 8
  ProductCategory Revenue Orders Avg_Order Customers Avg_Qty Revenue_Share  Rank
  <chr>             <dbl>  <int>     <dbl>     <int>   <dbl>         <dbl> <dbl>
1 Electronics       3000.      7     429.          6     1.1          79.4     1
2 Home Goods         266.      4      66.5         4     1.5           7       2
3 Books              262.      5      52.4         4     1.8           6.9     3
4 Clothing           252.      4      63.1         4     1.5           6.7     4

## 6. Putting It All Together: Business Dashboard

### 💼 What Is a Business Dashboard?

A **dashboard** is a one-page summary giving decision-makers key numbers at a glance. Tools like Tableau, Power BI, and Looker create the visual version — but **the data work behind every dashboard** is exactly what we've been doing: calculating, grouping, summarizing, and formatting.

### 📋 Our Dashboard Structure

| Section | What It Shows | Functions Used |
|---------|--------------|----------------|
| **Overall Metrics** | Total revenue, avg order, customer count | `summarize()` |
| **Top Products** | Revenue by category (ranked) | `group_by() + summarize() + arrange()` |
| **Regional Performance** | Revenue by region with % share | `group_by() + summarize() + mutate()` |
| **Customer Tiers** | Segment breakdown | `group_by() + summarize() + case_when()` |
| **Payment Methods** | Transaction count by type | `count()` |

In [30]:
# ================================================================
#                 BUSINESS INTELLIGENCE DASHBOARD
# ================================================================

cat("\n============================================================\n")
cat("          MONTHLY BUSINESS INTELLIGENCE DASHBOARD\n")
cat("          March 2024 | Customer Transaction Analysis\n")
cat("============================================================\n\n")

# --- SECTION 1: Overall Metrics ---
cat("OVERALL BUSINESS METRICS\n")
cat("------------------------------------------------------------\n")

overall <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  summarize(
    total_revenue = round(sum(TotalRevenue), 2),
    total_orders = n(),
    unique_customers = n_distinct(CustomerID),
    avg_order = round(mean(TotalRevenue), 2),
    median_order = round(median(TotalRevenue), 2),
    largest_order = max(TotalRevenue),
    smallest_order = min(TotalRevenue)
  )

cat("  Total Revenue:         $", format(overall$total_revenue, big.mark=","), "\n")
cat("  Total Orders:          ", overall$total_orders, "\n")
cat("  Unique Customers:      ", overall$unique_customers, "\n")
cat("  Average Order Value:   $", overall$avg_order, "\n")
cat("  Median Order Value:    $", overall$median_order, "\n")
cat("  Largest Order:         $", format(overall$largest_order, big.mark=","), "\n")
cat("  Smallest Order:        $", overall$smallest_order, "\n\n")

# --- SECTION 2: Top Product Categories ---
cat("TOP PRODUCT CATEGORIES (by Revenue)\n")
cat("------------------------------------------------------------\n")

top_products <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(ProductCategory) %>%
  summarize(revenue = round(sum(TotalRevenue), 2), orders = n(), .groups = 'drop') %>%
  mutate(share = round((revenue / sum(revenue)) * 100, 1)) %>%
  arrange(desc(revenue))

for(i in 1:nrow(top_products)) {
  cat("  ", i, ". ", top_products$ProductCategory[i],
      ": $", format(top_products$revenue[i], big.mark=","),
      " (", top_products$orders[i], " orders, ",
      top_products$share[i], "% of revenue)\n", sep="")
}

# --- SECTION 3: Regional Performance ---
cat("\nREGIONAL PERFORMANCE\n")
cat("------------------------------------------------------------\n")

regions <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(Region) %>%
  summarize(revenue = round(sum(TotalRevenue), 2),
            customers = n_distinct(CustomerID),
            avg_order = round(mean(TotalRevenue), 2),
            .groups = 'drop') %>%
  mutate(share = round((revenue / sum(revenue)) * 100, 1)) %>%
  arrange(desc(revenue))

for(i in 1:nrow(regions)) {
  cat("  ", regions$Region[i],
      ": $", format(regions$revenue[i], big.mark=","),
      " | ", regions$customers[i], " customers",
      " | Avg: $", regions$avg_order[i],
      " | ", regions$share[i], "%\n", sep="")
}

# --- SECTION 4: Customer Value Tiers ---
cat("\nCUSTOMER VALUE TIERS\n")
cat("------------------------------------------------------------\n")

tiers <- customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(CustomerID, CustomerName) %>%
  summarize(Total_Spent = sum(TotalRevenue), .groups = 'drop') %>%
  mutate(Tier = case_when(
    Total_Spent >= 500 ~ "Gold",
    Total_Spent >= 200 ~ "Silver",
    TRUE ~ "Bronze"
  )) %>%
  count(Tier) %>%
  mutate(pct = round((n / sum(n)) * 100, 1))

for(i in 1:nrow(tiers)) {
  cat("  ", tiers$Tier[i], ": ", tiers$n[i],
      " customers (", tiers$pct[i], "%)\n", sep="")
}

# --- SECTION 5: Payment Methods ---
cat("\nPAYMENT METHOD BREAKDOWN\n")
cat("------------------------------------------------------------\n")

payments <- customer_transactions %>%
  count(PaymentMethod, sort = TRUE) %>%
  mutate(pct = round((n / sum(n)) * 100, 1))

for(i in 1:nrow(payments)) {
  cat("  ", payments$PaymentMethod[i], ": ",
      payments$n[i], " orders (", payments$pct[i], "%)\n", sep="")
}

cat("\n============================================================\n")
cat("                    END OF DASHBOARD\n")
cat("============================================================\n")

============================================================
          MONTHLY BUSINESS INTELLIGENCE DASHBOARD
          March 2024 | Customer Transaction Analysis
============================================================

OVERALL BUSINESS METRICS
------------------------------------------------------------
  Total Revenue:         $ 3,780.24
  Total Orders:           20
  Unique Customers:       8
  Average Order Value:   $ 189.01
  Median Order Value:    $ 74.98
  Largest Order:         $ 1,099.99
  Smallest Order:        $ 16.99

TOP PRODUCT CATEGORIES (by Revenue)
------------------------------------------------------------
  1. Electronics: $2,999.92 (7 orders, 79.4% of revenue)
  2. Home Goods: $265.96 (4 orders, 7% of revenue)
  3. Books: $261.87 (5 orders, 6.9% of revenue)
  4. Clothing: $252.49 (4 orders, 6.7% of revenue)

REGIONAL PERFORMANCE
------------------------------------------------------------
  East: $1,779.88 | 2 customers | Avg: $296.65 | 47.1%
  North: $1,262.46 | 2 customers | Avg: $252.49 | 33.4%
  West: $534.93 | 2 customers | Avg: $106.99 | 14.2%
  South: $202.97 | 2 customers | Avg: $50.74 | 5.4%

CUSTOMER VALUE TIERS
------------------------------------------------------------
  Bronze: 3 customers (37.5%)
  Gold: 3 customers (37.5%)
  Silver: 2 customers (25%)

PAYMENT METHOD BREAKDOWN
------------------------------------------------------------
  Credit Card: 9 orders (45%)
  Debit Card: 6 orders (30%)
  Cash: 5 orders (25%)

============================================================
                    END OF DASHBOARD
============================================================

### 📖 What You Just Built

That dashboard used **every function** from Lessons 3 and 4:

| Function | Where It Was Used |
|----------|------------------|
| `mutate()` | Calculating TotalRevenue, Revenue Share %, Value Tiers |
| `summarize()` | Computing totals, averages, counts for each section |
| `group_by()` | Breaking down by ProductCategory, Region, CustomerID |
| `count()` | Payment method breakdown |
| `arrange()` | Sorting every section by the most important metric |
| `%>%` | Chaining everything into readable pipelines |

This is a text-based dashboard. In later lessons, you'll create the visual version with charts using ggplot2.

## Common Mistakes and How to Fix Them

Everyone makes these mistakes when learning. Knowing them in advance saves frustration.

---

### ⚠️ Top Mistakes to Avoid

| # | Mistake | What Goes Wrong | How to Fix It |
|---|---------|----------------|---------------|
| 1 | Forgetting `.groups = 'drop'` | Data stays grouped, weird results later | Always add `.groups = 'drop'` in `summarize()` |
| 2 | Using `=` instead of `==` in filter | `filter(x = 5)` causes an error | Use `filter(x == 5)` (double equals) |
| 3 | Forgetting `~` in case_when | `case_when(Amount > 100, "High")` fails | Use `case_when(Amount > 100 ~ "High")` |
| 4 | Missing `TRUE ~` in case_when | Unmatched rows become `NA` (blank) | Always end with `TRUE ~ "Default"` |
| 5 | Wrong order in case_when | Smaller condition catches big values | Put biggest/most restrictive condition first |
| 6 | Forgetting commas between columns in mutate | Syntax error | Separate each new column with a comma |
| 7 | Using a column before creating it | "Column not found" error | Inside `mutate()`, columns are created top-to-bottom |
| 8 | Forgetting `round()` | Output shows 12 decimal places | `round(value, 2)` for dollars, `round(value, 1)` for percentages |

---

### 🔧 case_when() Checklist

| ✅ Check | Correct | ❌ Wrong |
|----------|---------|----------|
| Uses `~` between condition and label | `Amount > 100 ~ "High"` | `Amount > 100, "High"` |
| Pairs separated by commas | `> 100 ~ "High", > 50 ~ "Med"` | Missing comma between pairs |
| `TRUE ~` as last catch-all | `TRUE ~ "Low"` | No `TRUE ~` → unmatched = `NA` |
| Labels in quotes | `~ "High"` | `~ High` (no quotes = error) |
| Biggest condition first | `> 200` first, then `> 100` | `> 100` first catches everything |

---

### 🔧 summarize() Checklist

| ✅ Check | Why |
|----------|-----|
| Used `.groups = 'drop'` | Prevents hidden grouping causing problems |
| Used `round()` on means and percentages | Clean output for reports |
| Gave descriptive metric names | `Total_Revenue` beats `x1` |
| Used `n_distinct()` for unique counts | `n()` counts rows; `n_distinct()` counts unique values |

## Summary and Next Steps

### 📚 What You Learned in This Lesson

| Function | Purpose | Example |
|----------|---------|---------| 
| `mutate()` | Create new calculated columns | `mutate(Total = Price * Qty)` |
| `if_else()` | Two-way label (inside mutate) | `if_else(Amount > 100, "High", "Low")` |
| `case_when()` | Multi-way label (inside mutate) | `case_when(Amount > 200 ~ "High", ...)` |
| `summarize()` | Collapse data to summary statistics | `summarize(AvgSale = mean(Amount))` |
| `group_by()` | Perform operations by group | `group_by(Region) %>% summarize(...)` |
| `count()` | Count rows per category | `count(ProductCategory, sort = TRUE)` |

---

### 🔑 Key Takeaways

| Concept | Remember |
|---------|----------|
| **mutate()** | Adds columns — never changes your original data |
| **Inside mutate(), order matters** | Column 2 can reference Column 1 if Column 1 was created first |
| **if_else()** | For two options: yes/no, high/low, pass/fail |
| **case_when()** | For three+ categories — uses `~`, always end with `TRUE ~` |
| **summarize()** | Collapses all rows to one summary row (or one per group) |
| **mean() vs. median()** | Mean is pulled by outliers; median gives the "typical" value |
| **group_by() + summarize()** | R's Pivot Table — splits data, then summarizes each group |
| **.groups = 'drop'** | Always include when using group_by + summarize |
| **count()** | Quick shortcut for "how many of each" |
| **Percentage pattern** | `round((value / sum(value)) * 100, 1)` works everywhere |
| **Pipe chains** | Chain mutate → group_by → summarize → mutate → arrange |

---

### 🔗 Complete dplyr Toolkit (Parts 1 + 2)

| Function | What It Does | Lesson |
|----------|-------------|--------|
| `select()` | Choose columns | Part 1 |
| `filter()` | Choose rows | Part 1 |
| `arrange()` | Sort rows | Part 1 |
| `mutate()` | Add calculated columns | Part 2 |
| `group_by()` | Split data into groups | Part 2 |
| `summarize()` | Calculate summary statistics | Part 2 |

---

### 🎯 
data %>% summarize(Total = sum(Amount), Avg = mean(Amount), Count = n())

# GROUP_BY + SUMMARIZE - Summary by category (Pivot Table)
data %>%
  group_by(Category) %>%
  summarize(Total = sum(Amount), Count = n(), .groups = 'drop')

# COUNT - Quick frequency count
data %>% count(Category, sort = TRUE)

# PERCENTAGE PATTERN - Works anywhere
data %>% mutate(Pct = round((Value / sum(Value)) * 100, 1))

# FULL PIPELINE - Complete business rQuick Reference Cheat Sheet

```r
# MUTATE - Add calculated columns
data %>% mutate(Total = Price * Quantity)
data %>% mutate(Flag = Amount > 100)
data %>% mutate(Label = if_else(Amount > 100, "High", "Low"))
data %>% mutate(Tier = case_when(
  Amount > 200 ~ "High",
  Amount > 100 ~ "Medium",
  TRUE ~ "Low"
))

# SUMMARIZE - Get summary numberseport
data %>%
  mutate(Total = Price * Qty) %>%
  group_by(Region) %>%
  group_by(Region) %>%
  group_by(Region) %>%
  summarize(Revenue = sum(Total),
            Orders = n(), .groups = 'drop') %>%
  mutate(Pct = round((Revenue/sum(Revenue))*100, 1)) %>%
  arrange(desc(Revenue))
```

---

### 📅 Coming Up Next

| Topic | What You'll Learn |
|-------|------------------|
| Joining Data | Combining data from multiple tables (like VLOOKUP in Excel) |
| Data Visualization | Creating charts and graphs with ggplot2 |
| Working with Dates | Analyzing trends by month, quarter, and year |

---

### 📝 Practice Exercises

Try these on your own using the `customer_transactions` dataset:

**mutate() exercises:**
1. Create `DiscountPrice` = `UnitPrice * 0.85` (15% off)
2. Create `BulkOrder` = `TRUE` when `Quantity > 1`
3. Create `ShippingTier` using `case_when()`: "Free" if TotalRevenue > 100, "Standard" if > 25, "Express" otherwise

**summarize() exercises:**
4. Find the total `Quantity` sold across all transactions
5. Find the `median` of `UnitPrice`

**group_by() exercises:**
6. Calculate the average `UnitPrice` by `Region`
7. Count transactions by `PaymentMethod` AND `Region`

**Combined pipeline:**
8. Group by `ProductCategory`, calculate total revenue and order count, add a percentage column, sort descending

**💡 Solution for Exercise 8:**
```r
customer_transactions %>%
  mutate(TotalRevenue = UnitPrice * Quantity) %>%
  group_by(ProductCategory) %>%
  summarize(
    Revenue = round(sum(TotalRevenue), 2),
    Orders = n(),
    .groups = 'drop'
  ) %>%
  mutate(Pct = round((Revenue / sum(Revenue)) * 100, 1)) %>%
  arrange(desc(Revenue))
```

In [ ]:
# YOUR PRACTICE SPACE
# Use this cell to try the practice exercises above!
# Remember: you can re-run earlier cells if you need to reload the data.